### ISSUE TITLE
[Feature] Next Stage scheduled

### ISSUE THREAD

**Issue by molesza** [dirkjanfaber/node-red-contrib-eskomsepush#7]
Thank you for your node which I have been enjoying.

I would like to suggest a feature though. I am currently setting my minimum stage of charge on my solar system depending on the current stage. This has been working flawlessly. I have been caught out though when the stage jumps and loadshedding starts immediately for 4 hours. It would be great if I could base my SOC based on whether the next scheduled stage is higher than the current stage. Could you add the next scheduled stage as an output?

Thanks

**Comment by dirkjanfaber** [comment]
Thanks. I am not 100% certain if I understand the request right. Please correct me when I am wrong.

I think that it is a matter of checking if there is a difference between `calc.stage` and `calc.next.stage`, in case the next shedding is because of an event.

That would end up look something like this:  
![image](https://github.com/dirkjanfaber/node-red-contrib-eskomsepush/assets/3098947/265e7a36-29db-46cb-bb84-f1dc552d4bb4)

Let me know if that seems about right.

**Comment by Johan-Bo** [comment]
Hi Dirkjanfaber

Can you please help me.
I'm trying to integrate with your EskomsePush by using your second output.
How and what do I use to get the start and end time of the current load-shedding as  well as the time for the next expected load-shedding.
I want to use this to switch off the inverter before load-shedding starts (10min prior) and reconnect the inverter after 10min once grid has returned.
I'm experiencing huge surges and want to avoid them before load-shedding happens and after grid returned.
The Eskomsepush node is up and running and is showing the current stage and time in my area just need to know how to get those info as mentioned above.

Kind Regards,
J

**Comment by dirkjanfaber** [comment]
@Johan-Bo : I would use the first output and look at `msg.calc.next.start` and `msg.calc.next.end` fields. Or perhaps even `msg.calc.secondstostatechange`

But I do not want to hijack this issue with something unrelated. So closing this one (as `isHigherState` has just been added to the latest release). Please file a new issue.
